# Site
title:              George Mamar
bio:                'George Mamar'
description:        "Hi! I'm George Mamar, a full-stack web developer."
reading_time:       true
words_per_minute:   180
logo:               '/assets/img/me.jpg'
bg2:                '/assets/img/bg2.jpg'
locale:             en_US
url:                "https://mamar.dev"
future:             false

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
email:              george@mamar.dev
twitter:            georgemamar
github-url:         georgem3
linkedin:           georgemamar
instagram:          mamar1of1
medium:            '@georgemamar'

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
